// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID        int32              `json:"id"`
	SlugID    string             `json:"slug_id"`
	Name      string             `json:"name"`
	OwnerID   int64              `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsDeleted bool               `json:"is_deleted"`
}

type BoardPage struct {
	ID        int32              `json:"id"`
	BoardID   int64              `json:"board_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsDeleted bool               `json:"is_deleted"`
}

type BoardUser struct {
	BoardID   int64              `json:"board_id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Role      string             `json:"role"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Token struct {
	Hash   []byte             `json:"hash"`
	UserID int64              `json:"user_id"`
	Expiry pgtype.Timestamptz `json:"expiry"`
	Scope  string             `json:"scope"`
}

type User struct {
	ID             int32              `json:"id"`
	FullName       string             `json:"full_name"`
	Email          string             `json:"email"`
	PasswordHash   []byte             `json:"password_hash"`
	IsVerified     pgtype.Bool        `json:"is_verified"`
	AuthProvider   string             `json:"auth_provider"`
	AuthProviderID pgtype.Text        `json:"auth_provider_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Version        int32              `json:"version"`
}

type UserPermission struct {
	UserID       int64 `json:"user_id"`
	PermissionID int64 `json:"permission_id"`
}
