// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/umtdemr/wb-backend/internal/worker (interfaces: Publisher)

// Package mockworker is a generated GoMock package.
package mockworker

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	worker "github.com/umtdemr/wb-backend/internal/worker"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// EnqueueJob mocks base method.
func (m *MockPublisher) EnqueueJob(arg0 context.Context, arg1 worker.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueJob indicates an expected call of EnqueueJob.
func (mr *MockPublisherMockRecorder) EnqueueJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueJob", reflect.TypeOf((*MockPublisher)(nil).EnqueueJob), arg0, arg1)
}
